export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN || '15m',
  REFRESH_TOKEN_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN || '30d',

  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,

  MAX_LOGIN_ATTEMPTS: 5,

  LOGIN_LOCK_TIME_MINUTES: 15,
} as const;