export enum NotificationType {
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_UPDATED = 'EXPENSE_UPDATED',
  SETTLEMENT_CREATED = 'SETTLEMENT_CREATED',
  SETTLEMENT_CONFIRMED = 'SETTLEMENT_CONFIRMED',
  GROUP_INVITATION = 'GROUP_INVITATION',
}
